# Site settings
author: Carrie
title: Thorns and Thunder
header-img: img/home-bg.png
email: c.jessica.jones@gmail.com
copyright_name: Carrie
description: > # this means to ignore newlines until "baseurl:"
  Truth, Beauty, Freedom, Love, Heavy Metal, and Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ThornlessRose3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
